### ISSUE TITLE
Registration Validation Issue - Email and Password errors not both showing

### ISSUE THREAD

**Issue by curringtpm17** [koenigbs18/PodChat#3]
Input-curringtpm17@uww.edu, test12345, 12
-(Wrong Output)- When both email is already used and password is less than 6 characters, it only shows the password is less than 6 characters error.

**Comment by paulknisely** [comment]
Issue resolved. When a known email and password with a length shorter than 6 is used, it now outputs the error

> The email you entered is already in use
> Password length is shorter than 6
