### ISSUE TITLE
Registration Validation Issue- username and password invalid inputs-only showing password error

### ISSUE THREAD

**Issue by curringtpm17** [koenigbs18/PodChat#4]
Input-test12345@uww.edu, curringtpm17, 12
-(Wrong Output)- When both username is already used and password is less than 6 characters, it only shows the password is less than 6 characters error.

**Comment by paulknisely** [comment]
Issue resolved. When a known username and a password with a length shorter than 6 is used, it now outputs the following error

> The username you entered is already in use
> Password length is shorter than 6
