### ISSUE TITLE
Registration Validation Issue- When all three inputs are invalid -  only password error shows

### ISSUE THREAD

**Issue by curringtpm17** [koenigbs18/PodChat#6]
Input-curringtpm17@uww.edu, curringtpm17, 12
-(Wrong Output)- When all three fields are entered in incorrectly, then just the password error shows up.

**Comment by paulknisely** [comment]
Issue resolved. When a known email, username, and a password with a length shorter than 6 is used, it now outputs the following error

> The email you entered is already in use
> The username you entered is already in use
> Password length is shorter than 6

also when all fields are empty, a

> FAILURE: INVALID REGISTRATION PARAMETERS

error pops up.
